version: '3.1'

services:
  db:
    image: mysql
    restart: always
    container_name: scrumpokerdb
    hostname: scrumpokerdb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gzCRGfwcMySLEJ88fA9d
      MYSQL_DATABASE: scrum_online
    networks:
      - so
    volumes:
      - ./db:/var/lib/mysql

  app:
    image: chrisns/scrumonline:latest
    restart: always
    container_name: scrumpokerapp
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      DB_NAME: scrum_online
      DB_USER: root
      DB_PASS: gzCRGfwcMySLEJ88fA9d
      DB_HOST: scrumpokerdb
      HOST: "http://localhost"
    networks:
      - so

networks:
  so:

